import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ToastProvider from "./components/ToastProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight:["100","200","300","400","500","600","700","800","900"]
});

export const metadata = {
  title: "E-commerce Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-arp="">
      <body
        className={`${poppins.variable} antialiased`}
        cz-shortcut-listen="true"
        >
        <Navbar/>
        <ToastProvider />
        {children}
      </body>
    </html>
  );
}
